Repository AY2425S2-CS2103T-W13-2/tp, pull requests merged in 2025-03, with the labels that each got.

#29 Update DeveloperGuide.md Use Cases
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#25 Update developer guide user stories, target user, and value proposition
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#27 Update developer guide glossary
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#38 Update README.md to remove traces of AB3
  README.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#47 Replace Person to Client further
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/client/UniqueClientList.java
  src/main/java/seedu/address/model/client/exceptions/ClientNotFoundException.java
  src/main/java/seedu/address/model/client/exceptions/DuplicateClientException.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/ClientCard.java
  src/main/java/seedu/address/ui/ClientListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditClientDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/client/ClientTest.java
  src/test/java/seedu/address/model/client/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/client/UniqueClientListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedClientTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
  src/test/java/seedu/address/testutil/ClientUtil.java
  src/test/java/seedu/address/testutil/EditClientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#53 Modify find command to find by category (tag) and product preference
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/client/predicates/CategoryContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/client/predicates/ClientSatisfyAllPredicate.java
  src/main/java/seedu/address/model/client/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/client/predicates/ProductPreferenceContainsKeywordsPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/ui/ClientCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/client/predicates/CategoryContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/client/predicates/ClientSatisfyAllPredicateTest.java
  src/test/java/seedu/address/model/client/predicates/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/client/predicates/ProductPreferenceContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedClientTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/stub/model/client/CategoryContainsKeywordsPredicateStub.java
  src/test/java/stub/model/client/NameContainsKeywordsPredicateStub.java
  src/test/java/stub/model/client/ProductPreferenceContainsKeywordsPredicateStub.java
Labels: type.Enhancement, type.Task, priority.High

#65 Change pref to optional and reset add command format
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/predicates/ProductPreferenceContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/ui/ClientCard.java
  src/test/java/seedu/address/storage/JsonAdaptedClientTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
Labels: type.Task, priority.High

#66 Add total purchase to UI
  src/main/java/seedu/address/ui/ClientCard.java
  src/main/resources/view/ClientListCard.fxml
  src/main/resources/view/DarkTheme.css
Labels: type.Task, priority.Medium

#60 Implement expand command
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExpandCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ExpandCommandParser.java
  src/main/java/seedu/address/ui/ClientDetailPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/ClientDetailPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Task, priority.Medium

#67 Modify Edit Command to accept Product Preference
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/EditClientDescriptorTest.java
Labels: priority.High

#68 Fix rank command example
  src/main/java/seedu/address/logic/commands/RankCommand.java
Labels: type.Task, priority.Medium, severity.Medium

#74 Fix jsonadaptedclient
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
Labels: type.Bug, priority.Medium, severity.Medium

#69 Update UserGuide.md Edit, List, Expand, Delete, Clear and Exit Command
  docs/UserGuide.md
  docs/images/ClearCommandUi.png
  docs/images/DeleteCommandUi_AfterDeleteResult.png
  docs/images/DeleteCommandUi_BeforeDeleteResult.png
  docs/images/EditCommandUi_AfterEditResult.png
  docs/images/EditCommandUi_BeforeEditResult.png
  docs/images/ExpandCommandUi.png
  docs/images/ListCommandUiResult.png
Labels: type.Task, priority.Medium

#73 Update UG v1.3 for rank and find command
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  docs/images/findClassmate.png
  docs/images/findClassmatesResult.png
  docs/images/findShampoo.png
  docs/images/findShampooFriendsResult.png
  docs/images/findShampooResult.png
  docs/images/findShampooThenRankName.png
  docs/images/listThenRankTotalResult.png
  docs/img.png
Labels: type.Task, priority.Medium

#75 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Bug

#76 Update Command Summary Table
  docs/UserGuide.md
Labels: type.Enhancement, priority.High

#82 Update_Ui
  src/main/java/seedu/address/ui/ClientDetailPanel.java
  src/main/resources/view/ClientDetailPanel.fxml
Labels: type.Task, priority.High

#83 Implement describe command and tests
  build.gradle
  src/main/java/seedu/address/logic/commands/DescribeCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DescribeCommandTest.java
  src/test/java/seedu/address/logic/commands/EditClientDescriptorTest.java
  src/test/java/seedu/address/testutil/EditClientDescriptorBuilder.java
Labels: type.Epic, priority.High

#89 create expand and expandParser test, update storage
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/test/java/seedu/address/logic/commands/ExpandCommandTest.java
  src/test/java/seedu/address/logic/parser/ExpandCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedClientTest.java
  src/test/java/seedu/address/testutil/TypicalClients.java
Labels: type.Task, priority.High

#91 Add DescribeCommandParser and related tests
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DescribeCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DescribeCommandTest.java
  src/test/java/seedu/address/logic/parser/DescribeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/EditClientDescriptorBuilder.java
Labels: type.Task, priority.High
