Repository AY2425S2-CS2103T-W13-2/tp, pull requests merged in 2025-04, with the labels that each got.

#103 Fix bug of parseFrequency
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: alpha-bug

#102 Fix bug parsePriority
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: alpha-bug

#120 Fix alpha bugs
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/Name.java
  src/main/java/seedu/address/model/client/Phone.java
  src/main/java/seedu/address/model/sortcomparators/NameComparator.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidClientAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidClientAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalClientsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/client/NameTest.java
  src/test/java/seedu/address/model/client/PhoneTest.java
  src/test/java/seedu/address/model/client/predicates/CategoryContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/client/predicates/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/client/predicates/ProductPreferenceContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalClients.java
Labels: alpha-bug

#121 Fix the bug where desc [INDEX] doesn't clear description
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Bug, priority.High, severity.Low, alpha-bug

#123 update ug quick start
  docs/UserGuide.md
Labels: type.Task, priority.High, severity.VeryLow

#125 add planned enhancements to DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.High, severity.VeryLow

#128 Update ClientDetailPnael java and fxml
  src/main/java/seedu/address/ui/ClientDetailPanel.java
  src/main/resources/view/ClientDetailPanel.fxml
Labels: alpha-bug

#131 Update HelpWindow.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: alpha-bug

#137 Update ParserClassDiagram and StorageClassDiagram
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Task, alpha-bug

#104 Update UML Class Diagram for Filter Command
  docs/diagrams/filter-command/FilterCommandClass.puml
  docs/diagrams/filter-command/FilterCommandParser.puml
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
Labels: type.Task, priority.Medium

#138 Update DG
  docs/DeveloperGuide.md
Labels: type.Task, alpha-bug

#147 Fix typo in message usage of filter command
  src/main/java/seedu/address/logic/commands/FilterCommand.java
Labels: severity.VeryLow, alpha-bug

#146 Update ExpandCommandUi.png
  docs/images/ExpandCommandUi.png
  src/main/java/seedu/address/ui/ClientDetailPanel.java
Labels: alpha-bug

#153 fix the bug where editing a client will set the description to empty
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/DescribeCommandParser.java
  src/main/java/seedu/address/model/client/Description.java
  src/test/java/seedu/address/logic/parser/DescribeCommandParserTest.java
  src/test/java/seedu/address/model/client/DescriptionTest.java
  src/test/java/seedu/address/storage/JsonAdaptedClientTest.java
Labels: type.Bug, priority.High, severity.High, alpha-bug

#217 add limitation to length of name and update userguide
  docs/UserGuide.md
  src/main/java/seedu/address/model/client/Name.java
  src/test/java/seedu/address/model/client/NameTest.java
Labels: type.Bug, alpha-bug

#218 Update Client.java, Filter error message, email domain must contain "." and FAQs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/Email.java
  src/test/java/seedu/address/model/client/ClientTest.java
  src/test/java/seedu/address/model/client/EmailTest.java
Labels: alpha-bug

#227 Fixed some tests which were disabled
  src/test/data/JsonSerializableAddressBookTest/typicalClientsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DescribeCommandTest.java
  src/test/java/seedu/address/logic/commands/EditClientDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/client/UniqueClientListTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
  src/test/java/seedu/address/testutil/ClientUtil.java
Labels: type.Task, priority.Medium, severity.Medium
